[package]
name = "chordprostyle"
version = "0.1.0"
authors = ["Miroslav Čech <miracech@email.cz>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
serde = {version = "1", features = ["derive"]}

[dependencies.tera]
version = "1"
default-features = false
